### ISSUE TITLE
Silence compilation warning

### ISSUE THREAD

**Issue by julianmrodri** [Tenderly/hardhat-tenderly#153]
Hi im getting these warnings every time I compile the project. How can I silence this? In our HH repo it is not mandatory to have Tenderly setup as it is only used for certain tasks, but not by default. 

Maybe a better option would be to be able to programmatically enable these Plugin checks and not do the `setup()` by default in `hardhat.config.ts` but couldnt find how to do this.

Any ideas? thanks!

```
2023-06-20 13:32:42.262 WARN Service =>Tenderly config doesn't exist, empty string values are returned instead.
2023-06-20 13:32:42.287 WARN Service =>Tenderly config doesn't exist, empty string values are returned instead.
```

**Comment by dule-git** [comment]
Hey @julianmrodri, thanks for reporting!

We don't have an option of loading the `setup()` by default.

The error you are getting is because you don't have the Tenderly Auth Configuration on your local machine.
This configuration should be found in `~/.tenderly/config.yaml`.

This configuration is populated by the `tenderly cli` when you run the `login` command.

The documentation can be found [here](https://github.com/Tenderly/tenderly-cli?tab=readme-ov-file#login).

I'll close the issue since this will resolve it for you. 😄
