### ISSUE TITLE
how to set contract name when verify?

### ISSUE THREAD

**Issue by jonah0000** [Tenderly/hardhat-tenderly#155]
Hi, guys. Our team is using Tenderly to manage our contract and using the hardhat as our development tool. I can't specialize the contract name when I verify a contract in hardhat task. Such as:
* Contract: Registry
* Address: 0x0000000000000
* The verify code: ``` tenderly.verify({ name: "Registry", address: "0x0000000000000" })```
* I want the contract name on tenderly to be RegistryV1.

**Comment by dule-git** [comment]
Hey @jonah0000,

Unfortunately, we don't support setting the contract name in the Tenderly project through `hardhat-tenderly`.
I'll write this down and we'll consider this mini-feature, but for now there are no plans to work on it.

Meanwhile, you can look at our [Tenderly SDK](https://docs.tenderly.co/tenderly-sdk/intro-to-tenderly-sdk) which has an `AddContractToProject` API that accepts `displayName`.

I'll close the issue since we don't have plans to work on it.
Thanks for letting us know your intentions! 😄
