### ISSUE TITLE
Configurable projects and networks in YAML config file

### ISSUE THREAD

**Issue by nkuba** [Tenderly/hardhat-tenderly#17]
Currently, it's possible to configure the project name to push the contracts in `hardhat.config.ts`. The plugin uses the same project for all the networks.
What would be amazing to have is [the same feature as `tenderly-cli` has, where it reads projects and networks configuration from a configuration YAML](https://github.com/Tenderly/tenderly-cli#advanced-usage).

**Comment by dule-git** [comment]
Hello @nkuba,

We are currently supporting verifying the contracts on a project provided in the `tenderly` config in `hardhat.config.ts`.
I'll close the issue since a lot of time has passed and there hasn't been any activity.

Please feel free to reopen the issue if you see a use-case that we don't support. 😄
