### ISSUE TITLE
Contracts tagging

### ISSUE THREAD

**Issue by nkuba** [Tenderly/hardhat-tenderly#19]
### Discussed in https://github.com/Tenderly/hardhat-tenderly/discussions/18

<div type='discussions-op-text'>

<sup>Originally posted by **nkuba** September  3, 2021</sup>
Hi,
Is it possible to set a tag at contract push or verification?

It's available in `tenderly-cli` with `--tag` flag.</div>

**Comment by dule-git** [comment]
Hello @nkuba,

We currently don't have the option of tagging the contract on the Tenderly project via `hardhat-tenderly`, and we don't have that feature on our roadmap.

You can check out our [SDK](https://docs.tenderly.co/tenderly-sdk/intro-to-tenderly-sdk), which has that kind of thing.

I'll close the issue since we don't plan to support this. 😄
