### ISSUE TITLE
How do I specify external library address while verifying contract

### ISSUE THREAD

**Issue by 134dd3v** [Tenderly/hardhat-tenderly#25]
```
npx hardhat --network arbtest tenderly:verify ContractName=0xAddr
```

My `ContractName` deployed at `0xAddr` also includes some external libraries. Maybe that's why I get the following error:

```
Error in hardhat-tenderly: There was an error during the request. Contract verification failed
```

Is there a way I can specify the library address?

**Comment by dule-git** [comment]
Hey @134dd3v,

Even though the `tenderly:verify` task now supports adding libraries to the command, it is a very tricky syntax.

I suggest moving to the `hardhat-tenderly` plugin and its automatic verification feature.
Or using the `hre.tenderly.verify` API in order to verify contracts.

I'll close the issue for now since a lot of time has passed, but feel free to reopen it if you are still having problems.
